# Generated by Django 4.0.4 on 2022-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='gallery_image',
            field=models.ImageField(default=1, unique=True, upload_to='articles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image_description',
            field=models.CharField(max_length=200),
        ),
    ]
