# Generated by Django 4.0.4 on 2022-05-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_category_images_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='names',
        ),
    ]
