# Generated by Django 4.0.4 on 2022-05-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='names',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='images',
            name='category',
        ),
        migrations.AddField(
            model_name='images',
            name='image_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery_app.category'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery_app.location'),
        ),
        migrations.AlterField(
            model_name='images',
            name='gallery_image',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
    ]
