# Generated by Django 4.0.4 on 2022-05-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0007_remove_images_image_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery_app.location'),
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_category',
        ),
        migrations.AddField(
            model_name='images',
            name='image_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery_app.category'),
        ),
    ]
